name: food_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.1
  intl: ^0.20.2
  firebase_storage: ^12.4.4
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  get_storage: ^2.1.1
  logger: ^2.5.0
  iconsax: ^0.0.8
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/dishes/
    - assets/images/onboarding/
    - assets/icons/payment_methods/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logos/logo.png'